# Generated by Django 5.1.5 on 2025-01-22 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprocess_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='is_internal',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprocess_app.server'),
        ),
    ]
