# Generated by Django 5.1.5 on 2025-01-31 18:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprocess_app', '0002_remove_deployment_is_internal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('commit_id', models.CharField(blank=True, max_length=40, null=True)),
                ('commit_message', models.TextField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('ignored', 'Ignored')], max_length=20)),
                ('deployment_message', models.TextField(blank=True, null=True)),
                ('files_changed', models.JSONField(blank=True, default=dict)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_logs', to='subprocess_app.deployment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
