# Generated by Django 5.1.5 on 2025-02-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprocess_app', '0003_gitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='pass_deploy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
