# Generated by Django 5.1.5 on 2025-02-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subprocess_app', '0004_deployment_pass_deploy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='status',
        ),
    ]
