# Generated by Django 5.1.5 on 2025-02-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprocess_app', '0005_remove_deployment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='github_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='webhook_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
